# Default values for Label Studio Dev Deployment

# Set PG_TRGM within Azure Postres Server parameters
# Source: https://github.com/HumanSignal/label-studio/issues/4310#issuecomment-1678207349

global:
  imagePullSecrets: []

  image:
    repository: heartexlabs/label-studio
    pullPolicy: IfNotPresent
    tag: ""

  pgConfig:
    # host: "ns-ii-tech-dev-pg-srv.postgres.database.azure.com"
    port: 5432
    dbName: "labelstudio"
    # userName: "naturalstate"
    # password:
    #   secretName: postgres-dev-labelstudio
    #   secretKey: pgpassword

  extraEnvironmentVars:
    SKIP_DB_MIGRATIONS: true
  
app:
  ingress:
    enabled: true
    className: ""
    annotations:
      traefik.ingress.kubernetes.io/ssl-redirect: "true"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    path: /
    extraPaths: []
    pathType: ImplementationSpecific
    tls:
      - hosts:
        - ls-dev.naturalstate.tech
        secretName: ingress-tls-labelstudio
    extraHosts: [ ]

traefik:
  enabled: true
  ports:
    web:
      redirectTo:
        port: websecure
  service:
    externalIPs:
  ssl:
    enabled: true

